
stages:
  - build
  - test
#  - deploy

build-develop:
  except:
      - master
      - tags
  stage: build
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: $CI_BUILDS_DIR/openapi4restxq
  script:
    - pwd
    - cd $GIT_CLONE_PATH
    - yarn install
#    - ant test
#  artifacts:
#    paths:
#      - build/*.xar
#      - test/

#build-master:
#  only:
#      - master
#  stage: build
#  script:
#    - cp master.build.properties local.build.properties
#    - npm install
#    - ant test
#  artifacts:
#    paths:
#      - build/*.xar
#      - test/
#
installation:
  except:
      - master
      - tags
  stage: build
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: $CI_BUILDS_DIR/openapi4restxq
  script:
    - cd $GIT_CLONE_PATH
    - yarn install
    - |
      patch <<EOF
      --- resources/swagger-ui-dist/index.html        2019-05-28 16:35:33.341000000 +0200
      +++ index.html  2019-05-28 17:48:45.573077200 +0200
      @@ -41,3 +41,3 @@
             const ui = SwaggerUIBundle({
      -        url: "https://petstore.swagger.io/v2/swagger.json",
      +        url: "openapi.json",
               dom_id: '#swagger-ui',
      EOF
    - cd $CI_BUILDS_DIR
    - mkdir screenshots
    - cd screenshots
    - chromium-browser --headless --disable-gpu --no-sandbox --screenshot --window-size=1280,1696 --virtual-time-budget=10000 http://localhost:8984/openapi
    - mv screenshot.png openapi4restxq.png
  artifacts:
    paths:
      - $CI_BUILDS_DIR/screenshots

#upload:
#  only:
#      - master
#      - develop
#  except:
#      - tags
#  stage: deploy
#  script:
#    - FILENAME=$(ls build/*.xar)
#    - curl -u ci:${EXIST_UPLOAD_PW} -X POST -F file=@${FILENAME} https://ci.de.dariah.eu/exist-upload
