stages:
  - build
  - test
#  - deploy

build-develop:
  tags:
      - existdb4x
  except:
      - master-acdh
      - tags
  stage: build
  script:
    - npm install
    - ant test
  artifacts:
    paths:
      - build/*.xar
      - test/

build-master:
  tags:
      - existdb4x
  only:
      - master-acdh
  stage: build
  script:
    - cp master.build.properties local.build.properties
    - npm install
    - ant test
  artifacts:
    paths:
      - build/*.xar
      - test/

installation:
  tags:
      - existdb4x
  except:
      - tags
  stage: test
  script:
    - '# check for exist (it is already running)'
    - while [ $(curl --head --silent http://localhost:8080 | grep -c "200 OK") == 0 ]; do sleep 2s; done
    - ls -al /tmp; mv /tmp/tests-* . || true
  artifacts:
    paths:
      - test/tests-*.xml
      - test/eXist-db-*/webapp/WEB-INF/logs/expath-repo.log
    reports:
        junit: test/tests-*.xml

#upload:
#  only:
#      - master-acdh
#      - develop
#  except:
#      - tags
#  stage: deploy
#  script:
#    - FILENAME=$(ls build/*.xar)
#    - curl -u ci:${EXIST_UPLOAD_PW} -X POST -F file=@${FILENAME} https://ci.de.dariah.eu/exist-upload
