stages:
  - build
  - test
#  - deploy

build-develop:
  tags:
      - existdb4x
  except:
      - master-acdh
      - tags
  stage: build
  variables:
     GIT_STRATEGY: clone
     HOME: /home/gitlab-runner
  script:
    - npm install
    - ant test
  artifacts:
    paths:
      - build/*.xar
      - test/

build-master:
  tags:
      - existdb4x
  only:
      - master-acdh
  stage: build
  variables:
     GIT_STRATEGY: clone
     HOME: /home/gitlab-runner
  script:
    - cp master.build.properties local.build.properties
    - npm install
    - ant test
  artifacts:
    paths:
      - build/*.xar
#      - test/ contains only an exist-db 4.6.1

installation:
  tags:
      - existdb4x
  except:
      - tags
  stage: test
  variables:
     GIT_STRATEGY: fetch
     HOME: /home/gitlab-runner
  script:
    - '# check for exist (it is already running)'
    - while [ $(curl --head --silent http://localhost:8080 | grep -c "200 OK") == 0 ]; do sleep 2s; done
    - |
      # Install the xar from build/
      client.sh -s -u admin -P $EXIST_PASSWORD -x "
      xquery version '3.1';
      import module namespace repo='http://exist-db.org/xquery/repo';  
      let \$app := (xmldb:create-collection('/db', 'xars-to-deploy'),
      xmldb:store-files-from-pattern('/db/xars-to-deploy', '$GIT_CLONE_PATH/build', '*.xar', 'application/octet-stream'))[2]
      return (
        try {
         repo:undeploy('https://lab.sub.uni-goettingen.de/restxqopenapi'),
         repo:remove('https://lab.sub.uni-goettingen.de/restxqopenapi')
        } catch * {()},
       repo:install-and-deploy-from-db(\$app, 'https://lab.sub.uni-goettingen.de/restxqopenapi'),
       xmldb:remove('/db/xars-to-deploy')
      )
      "
  artifacts:
    paths:
      - test/tests-*.xml
      - test/eXist-db-*/webapp/WEB-INF/logs/expath-repo.log
    reports:
        junit: test/tests-*.xml

#upload:
#  only:
#      - master-acdh
#      - develop
#  except:
#      - tags
#  stage: deploy
#  script:
#    - FILENAME=$(ls build/*.xar)
#    - curl -u ci:${EXIST_UPLOAD_PW} -X POST -F file=@${FILENAME} https://ci.de.dariah.eu/exist-upload
