stages:
  - build
  - test
  - deploy

build-develop:
  tags:
      - existdb4x
  except:
      - master-acdh
      - tags
  stage: build
  variables:
     GIT_STRATEGY: clone
     HOME: /home/gitlab-runner
  script:
    - npm install
    - ant test
  artifacts:
    paths:
      - build/*.xar
      - test/

build-master:
  tags:
      - existdb4x
  only:
      - master-acdh
  stage: build
  variables:
     GIT_STRATEGY: clone
     HOME: /home/gitlab-runner
  script:
    - cp master.build.properties local.build.properties
    - ant test
  artifacts:
    paths:
      - build/*.xar

installation:
  tags:
      - existdb4x
  except:
      - tags
  stage: test
  variables:
     GIT_STRATEGY: fetch
     HOME: /home/gitlab-runner
  script:
    - '# check for exist (it is already running)'
    - while [ $(curl --head --silent http://localhost:8080 | grep -c "200 OK") == 0 ]; do sleep 2s; done
    - GIT_CLONE_PATH=$(pwd)
    - echo $CI_BUILDS_DIR =\> $GIT_CLONE_PATH
    - |
      # Install the xar from build/
      client.sh -s -u admin -P $EXIST_PASSWORD -x "
      xquery version '3.1';
      import module namespace repo='http://exist-db.org/xquery/repo';  
      let \$app := (xmldb:create-collection('/db', 'xars-to-deploy'),
      xmldb:store-files-from-pattern('/db/xars-to-deploy', '$GIT_CLONE_PATH/build', '*.xar', 'application/octet-stream'))[2]
      return (
        try {
         repo:undeploy('https://lab.sub.uni-goettingen.de/openapi4restxq'),
         repo:remove('https://lab.sub.uni-goettingen.de/openapi4restxq')
        } catch * {concat('Could not uninstall: ',\$err:description)},
       repo:install-and-deploy-from-db(\$app, 'https://lab.sub.uni-goettingen.de/openapi4restxq'),
       xmldb:remove('/db/xars-to-deploy')
      )
      "
    - mkdir screenshots-actual
    - mkdir screenshots-diff
    - cd screenshots-actual
    - chromium-browser --headless --disable-gpu --no-sandbox --screenshot --window-size=1280,1696 --virtual-time-budget=10000 http://localhost:8080/exist/apps/openapi
    - mv screenshot.png openapi4restxq.png
    - diffpng --output ../screenshots-diff/openapi4restxq openapi4restxq.png ../screenshots/openapi4restxq.png

  artifacts:
    when: on_failure
    expire_in: 1 day
    paths:
      - screenshots-actual
      - screenshots-diff
#upload:
#  only:
#      - master-acdh
#      - develop
#  except:
#      - tags
#  stage: deploy
#  script:
#    - FILENAME=$(ls build/*.xar)
#    - curl -u ci:${EXIST_UPLOAD_PW} -X POST -F file=@${FILENAME} https://ci.de.dariah.eu/exist-upload
clean-testbench:
  stage: deploy
  tags:
      - existdb4x
  script:
    - |
      # Install the xar from build/
      client.sh -s -u admin -P $EXIST_PASSWORD -x "
      xquery version '3.1';
      import module namespace repo='http://exist-db.org/xquery/repo';
        try {
         repo:undeploy('https://lab.sub.uni-goettingen.de/openapi4restxq'),
         repo:remove('https://lab.sub.uni-goettingen.de/openapi4restxq'),
          'Uninstalled test data.'
        } catch * {concat('Could not uninstall: ',\$err:description)}
      "
