
stages:
  - build
  - test
#  - deploy

build-develop:
  except:
      - master
      - tags
  stage: build
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: /opt/basex/webapp
  script:
    - yarn install
#    - ant test
#  artifacts:
#    paths:
#      - build/*.xar
#      - test/

#build-master:
#  only:
#      - master
#  stage: build
#  script:
#    - cp master.build.properties local.build.properties
#    - npm install
#    - ant test
#  artifacts:
#    paths:
#      - build/*.xar
#      - test/
#
installation:
  except:
      - master
      - tags
  stage: build
  tags:
      - BaseX-9.2
  variables:
     GIT_CLONE_PATH: /opt/basex/webapp
  script:
    - yarn install
  artifacts:
    paths:
      - /opt/basex/webapp/openapi4restxq

#upload:
#  only:
#      - master
#      - develop
#  except:
#      - tags
#  stage: deploy
#  script:
#    - FILENAME=$(ls build/*.xar)
#    - curl -u ci:${EXIST_UPLOAD_PW} -X POST -F file=@${FILENAME} https://ci.de.dariah.eu/exist-upload
